version: "3"
services:
  grader:
    image: palyvos/debs-2020-challenge-grader
    container_name: benchmark-grader
    environment:
      HARD_TIMEOUT_SECONDS: 25000
      DATASET_PATH: "/dataset"
      GRADER_CACHE_ENABLED: "True"
    volumes:
      - /home/runqi/Workspace/Spring2020/CS591K1/challenge/dataset2:/dataset # modify to load your dataset path
    networks:
      - bench

  solution:
    image: dsprocks2020/solution # YOUR_DOCKERHUB_IMAGE_ID (e.g., palyvos/baseline-solution)
    environment:
      BENCHMARK_SYSTEM_URL: "grader"
    depends_on:
      - grader
    networks:
      - bench

networks:
  bench: {}
